---
title: "Vaccination Rates and COVID mortality in Chicago"
author: William F Parker, MD, MS
output:
  html_document:
    theme: darkly
--- 

```{r global_options, include=FALSE, cache = FALSE}
library(knitr)
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, linewidth=60, cache= TRUE)
library(tidyverse)
library(ggpubr)
library(sf)
library(tigris)
library(tidycensus)
options(tigris_use_cache = TRUE)
```

```{r}
#zip_codes <- zctas(cb = TRUE, starts_with = 60, class = "sf")

#save(file = "zip_code_data.R", zip_codes)

load("zip_code_data.R")
```


```{r}
zips_sf <- zip_codes %>%
  select(zip = ZCTA5CE10, geometry)
```

```{r}
vax_data_by_zip <- read_csv("https://data.cityofchicago.org/api/views/553k-3xzc/rows.csv?accessType=DOWNLOAD") %>%
  mutate(zip = `Zip Code`) %>% 
  select(zip, `Total Doses - Daily`, Population) %>%
  group_by(zip) %>%
  summarise(total_vax = sum(`Total Doses - Daily`),
            population = mean(Population)) %>%
  mutate(pct_vax = total_vax/population)
```


```{r}
covid_by_zip <- read_csv("https://data.cityofchicago.org/api/views/yhhz-zm2v/rows.csv?accessType=DOWNLOAD") %>%   
  mutate(zip = `ZIP Code`) %>%
  group_by(zip) %>% 
  summarise(total_cases = sum(`Cases - Weekly`, na.rm =  TRUE ),
            case_rate = max(`Case Rate - Cumulative`,  na.rm =  TRUE),
              death_rate = max(`Death Rate - Cumulative`),
            total_deaths = sum(`Deaths - Weekly`),
            population = mean(Population)
  ) 
```


```{r}
to_map <- vax_data_by_zip %>% 
  left_join(covid_by_zip %>% select(zip, death_rate)) %>%
  select(zip, pct_vax, death_rate) %>% 
  filter(is.infinite(pct_vax) == FALSE)
```


```{r}

plot_A <- zips_sf %>%
  left_join(to_map) %>% 
  filter(is.na(pct_vax) == FALSE) %>%
  ggplot(aes(geometry = geometry, fill = 100*pct_vax)) + 
  geom_sf() + 
  theme_void() + coord_sf() + 
  scale_fill_distiller(direction = 1, limits = c(0, 100*max(to_map$pct_vax))) + 
  #scale_fill_viridis_c(direction = -1) +
  labs(fill = "Residents Vaccinated (%)") +
  theme(legend.position = "bottom")
```

```{r}
plot_B <- zips_sf %>%
  left_join(to_map) %>% 
  filter(is.na(pct_vax) == FALSE) %>%
  ggplot(aes(geometry = geometry, fill = death_rate)) + 
  geom_sf() + 
  theme_void() + coord_sf() + 
  scale_fill_distiller(direction = 1, limits = c(0, max(to_map$death_rate)), palette = "Reds") + 
  #scale_fill_viridis_c(option = "inferno") +
  labs(fill = "Mortality rate\n(deaths/100,000)") +
    theme(legend.position = "bottom")
```

# Data Sources

* [Vaccine source data](https://data.cityofchicago.org/Health-Human-Services/COVID-19-Vaccine-Doses-by-ZIP-Code-1st-Dose/c28u-q29v) 
* [Mortality source data](https://data.cityofchicago.org/Health-Human-Services/COVID-19-Cases-Tests-and-Deaths-by-ZIP-Code/yhhz-zm2v)

Last updated at `r format(Sys.Date(),'%A, %B %d')` at `r format(Sys.time(), '%I:%M %p')` CST. Death and vaccination rates are cumulative to date.

# Map
```{r}
ggarrange(plot_B, plot_A)

ggsave("vax_death_map_chicago.pdf")



```

# Correlation
```{r}
to_map %>%
  ggplot(aes(x = death_rate, y = 100*pct_vax))+
  geom_point() + labs(x = "Deaths per 100,000 residents", y = "Residents vaccinated (%)")
```

The correlation between morality and vaccination is `r cor(to_map$pct_vax, to_map$death_rate) %>% format(digits =2 )`







